source 'https://rubygems.org'

gem 'rails', '4.1.8'
gem 'pg'
gem 'devise'

gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development


