source 'https://rubygems.org'

#ruby '2.1.5'

gem 'rails', '4.1.8'
gem 'pg'
gem 'devise'
gem 'rack-cors', :require => 'rack/cors'
gem 'active_model_serializers', '~> 0.8.0'
gem 'newrelic_rpm'
gem 'paper_trail'
gem 'apartment'

group :production do
  gem 'rails_12factor'
end